options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'test-cicd'
      - '--runtime=python310'
      - '--service-account=$_FUNCTION_SERVICE_ACCOUNT@$_PROJECT_ID.iam.gserviceaccount.com'
      - '--trigger-http'
      - '--region=$_REGION'
      - '--entry-point=$_FUNCTION_ENTRY_POINT'
      - '--gen2'
